name: pre-commit

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - dev

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.12"
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Run pre-commit (auto-fix and retry)
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
